"""Utility functions for FortiManager MCP server.

This package provides:
- errors: Custom exception classes for error handling
- validation: Input validation and sanitization utilities
- config: Configuration management
"""

from fortimanager_mcp.utils.errors import (
    ADOMLockError,
    APIError,
    AuthenticationError,
    ConnectionError,
    DeviceError,
    FortiManagerMCPError,
    InstallError,
    ObjectError,
    PackageError,
    PermissionError,
    PolicyError,
    ResourceNotFoundError,
    ScriptError,
    TaskError,
    TemplateError,
    TimeoutError,
    ValidationError,
    is_auth_error,
    is_duplicate_error,
    is_object_in_use_error,
    is_permission_error,
    parse_fmg_error,
)
from fortimanager_mcp.utils.validation import (
    ValidationError as InputValidationError,
)
from fortimanager_mcp.utils.validation import (
    sanitize_for_logging,
    sanitize_json_for_logging,
    validate_address_type,
    validate_adom,
    validate_device_name,
    validate_device_serial,
    validate_filename,
    validate_fqdn,
    validate_interface_name,
    validate_ipv4_address,
    validate_ipv4_subnet,
    validate_log_traffic_mode,
    validate_move_position,
    validate_ngfw_mode,
    validate_object_name,
    validate_output_path,
    validate_package_name,
    validate_policy_action,
    validate_policy_id,
    validate_policy_name,
    validate_port_range,
    validate_status,
)

__all__ = [
    # Error classes
    "FortiManagerMCPError",
    "AuthenticationError",
    "ConnectionError",
    "APIError",
    "ValidationError",
    "ResourceNotFoundError",
    "PermissionError",
    "TimeoutError",
    "ADOMLockError",
    "TaskError",
    "PolicyError",
    "PackageError",
    "ObjectError",
    "TemplateError",
    "ScriptError",
    "DeviceError",
    "InstallError",
    # Error utilities
    "parse_fmg_error",
    "is_object_in_use_error",
    "is_duplicate_error",
    "is_permission_error",
    "is_auth_error",
    # Validation
    "InputValidationError",
    "sanitize_for_logging",
    "sanitize_json_for_logging",
    "validate_adom",
    "validate_device_name",
    "validate_device_serial",
    "validate_package_name",
    "validate_policy_name",
    "validate_object_name",
    "validate_interface_name",
    "validate_ipv4_address",
    "validate_ipv4_subnet",
    "validate_fqdn",
    "validate_port_range",
    "validate_policy_action",
    "validate_log_traffic_mode",
    "validate_status",
    "validate_ngfw_mode",
    "validate_address_type",
    "validate_move_position",
    "validate_policy_id",
    "validate_output_path",
    "validate_filename",
]
